#!/bin/bash
set -euo pipefail

HERE=$(realpath $(dirname $0))
CC=$HOME/.claude

rm -fr $HERE/skills && cp -r $CC/skills $HERE/skills
cp $CC/CLAUDE.md $HERE/CLAUDE.md
cp $CC/settings.json $HERE/settings.json
