#!/bin/sh

set -eu

echo "🕒$(date '+%Y-%m-%d %H:%M:%S (%Z)')"

# https://app.link.com/purchases
if [[ $(date +%-d) -lt 6 ]]; then
  since=$(date -v-1m +%Y%m06)
  until=$(date +%Y%m06)
else
  since=$(date +%Y%m06)
  until=$(date -v+1m +%Y%m06)
fi
ccusage -j -s $since -u $until | jq -r '"💰\(.totals.totalCost * 100 | round / 100) (USD)"'

brew_outdated=$(
  brew info --installed --json=v2 | jq -r '(
    (.formulae | map(select((.outdated) and (.installed | any(.installed_on_request))) | .name)) +
    (.casks | map(select(.outdated) | .token))
  ) | join(", ")'
)
if [[ -n $brew_outdated ]]; then
  echo "🍺[OUTDATED] $brew_outdated"
fi

npm_outdated=$(npm outdated -g --json | jq -r 'keys | join(", ")')
if [[ -n $npm_outdated ]]; then
  echo "📦[OUTDATED] $npm_outdated"
fi
