#!/bin/sh

set -eu

# https://brew.sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# https://github.com/Homebrew/homebrew-bundle/blob/cc9747cd3b28628b6d70789c7c6a97d675dd1ff1/cmd/bundle.rb
brew bundle --file=$HOME/dotfiles/brew/Brewfile -v

# https://qiita.com/s_Pure/items/9b90155d8e3e545c0733
brew link --overwrite git
