#!/bin/sh

set -eu

mkdir .memo
defaults read > .memo/$(date +%s).txt

defaults write -g AppleShowAllExtensions -bool true
defaults write -g InitialKeyRepeat -int 10 # 150ms
defaults write -g KeyRepeat -int 1 # 15ms
defaults write -g NSAutomaticCapitalizationEnabled -bool false
defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
defaults write -g NSAutomaticTextCompletionEnabled -bool false
defaults write -g WebAutomaticSpellingCorrectionEnabled -bool false
defaults write -g com.apple.mouse.scaling -int 3
defaults write -g com.apple.scrollwheel.scaling -float 0.4
defaults write -g com.apple.swipescrolldirection -bool false
defaults write -g com.apple.trackpad.forceClick -bool false
defaults write -g com.apple.trackpad.scaling -int 3
defaults write -g com.apple.trackpad.scrolling -float 0.4

defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
defaults write com.apple.HIToolbox AppleCapsLockPressAndHoldToggleOff -bool false
defaults write com.apple.HIToolbox AppleDictationAutoEnable -bool false
defaults write com.apple.HIToolbox AppleFnUsageType -bool false
defaults write com.apple.assistant.support "Assistant Enabled" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible BentoBox" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Bluetooth" -bool true
defaults write com.apple.controlcenter "NSStatusItem Visible Display" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible FocusModes" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible NowPlaying" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible ScreenMirroring" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Sound" -bool true
defaults write com.apple.controlcenter "NSStatusItem Visible UserSwitcher" -bool false
defaults write com.apple.controlstrip FullCustomized -array \
  "com.apple.system.group.keyboard-brightness" \
  "com.apple.system.group.brightness" \
  "com.apple.system.mission-control" \
  "com.apple.system.group.volume"
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.dock largesize -int 128
defaults write com.apple.dock mru-spaces -bool false
defaults write com.apple.dock orientation -string "right"
defaults write com.apple.dock show-process-indicators -bool true
defaults write com.apple.dock show-recents -bool false
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults write com.apple.finder AppleShowAllFiles -bool true
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
defaults write com.apple.finder "NSWindowTabbingShoudShowTabBarKey-com.apple.finder.TBrowserWindow" -bool true
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file:///$HOME/Downloads/"
defaults write com.apple.finder ShowMountedServersOnDesktop -bool false
defaults write com.apple.finder ShowRecentTags -bool false
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool false
defaults write com.apple.menuextra.battery ShowPercent -bool true
defaults write com.apple.menuextra.clock Show24Hour -bool true
defaults write com.apple.menuextra.clock ShowDate -bool true
defaults write com.apple.menuextra.clock ShowDayOfWeek -bool true
defaults write com.apple.menuextra.clock ShowSeconds -bool true
defaults write com.apple.screencapture name ss

defaults read > .memo/$(date +%s).txt

networksetup -setdnsservers Wi-Fi 1.1.1.1 8.8.4.4 8.8.8.8
networksetup -setv6off Wi-Fi

sudo defaults write /Library/Preferences/com.apple.alf globalstate -bool true
sudo shutdownn -r now
