#!/bin/sh

set -e

# シンボリックリンクを貼る
if [ ! -f $HOME/.zshrc ]; then
  ln -s $HOME/dotfiles/.zshrc $HOME/.zshrc
fi

if [ ! -f $HOME/.config/starship.toml ]; then
  ln -s $HOME/dotfiles/starship.toml $HOME/.config/starship.toml
fi

if [ ! -f $HOME/.gitconfig ]; then
  ln -s $HOME/dotfiles/.gitconfig $HOME/.gitconfig
fi

if [ ! -d $HOME/.config/git ]; then
  mkdir $HOME/.config/git
  if [ ! -f $HOME/.config/git/ignore ]; then
    ln -s $HOME/dotfiles/config_git_ignore $HOME/.config/git/ignore
  fi
fi

# フォントをインストール
# https://qiita.com/mktktmr/items/5481eac60b96c80cc262
if [ ! -d $HOME/Library/Fonts ]; then
  brew tap sanemat/font
  brew install ricty --with-powerline
  cp -f /usr/local/opt/ricty/share/fonts/Ricty*.ttf ~/Library/Fonts/
  fc-cache -vf
fi

# Homebrewをインストール
if [ ! -f /usr/local/bin/brew ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  sudo chown -R $(whoami):admin /usr/local/*
fi

# Brewfileにある物をインストール
brew bundle -v --file $HOME/dotfiles/Brewfile

# https://qiita.com/s_Pure/items/9b90155d8e3e545c0733
brew link --overwrite git
