#!/bin/bash
set -euo pipefail
trap '[[ $? -eq 0 ]] && echo "✅$0" || echo "❌$0"' EXIT

command=${1:-undefined}
commands=(doctor setup)
if [[ ! " ${commands[@]} " =~ " $command " ]]; then
  echo "⚠️ (${commands[@]}) required"
  exit 1
fi

error=0
run () {
  if [[ $command == 'setup' ]]; then
    echo "🚀$0:${BASH_LINENO[0]} $1"
    eval $1 || exit $?
  else
    echo "⚠️ $0:${BASH_LINENO[0]} $1"
    error=1
  fi
}

if [[ ! $(command -v brew) ]]; then
  # https://brew.sh/
  run '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  run '(echo; echo '\''eval "$(/opt/homebrew/bin/brew shellenv)"'\'') >> $HOME/.zprofile'
fi

if [[ ! $(command -v mise) ]]; then
  # https://github.com/Homebrew/brew/blob/master/docs/Manpage.md
  run 'brew bundle --file=$HOME/dotfiles/Brewfile'
fi

if [[ $(git -v) == *Apple* ]]; then
  # https://qiita.com/s_Pure/items/9b90155d8e3e545c0733
  run 'brew link --overwrite git'
fi

mkdir -p $HOME/.config/git
mkdir -p $HOME/.ssh
files=(
  .config/git/config
  .config/git/ignore
  .config/starship.toml
  .ssh/config
  .npmrc
  .zshrc
)
printf '%s\n' ${files[@]} | while read file; do
  if [[ $(readlink $HOME/$file) != $HOME/dotfiles/home/$file ]]; then
    run 'ln -fsv $HOME/dotfiles/home/$file $HOME/$file' | {
      [[ $command == 'doctor' ]] && tr -d '\n' && echo "（$file）" || cat
    }
  fi
done

if [[ ! $(cat $HOME/.zprofile) =~ 'SHELL_SESSIONS_DISABLE=1' ]]; then
  # https://superuser.com/questions/1610587/disable-zsh-session-folder-completely
  run 'rm -fr $HOME/.zsh_sessions && echo '\''\nexport SHELL_SESSIONS_DISABLE=1'\'' >> $HOME/.zprofile'
fi

exit $error
