[directory]
truncation_length = 100
truncate_to_repo = false

[git_status]
# conflicted = "🏳"
ahead = "⇡${count}/"
behind = "⇣${count}/"
diverged = "/"
untracked = "new/"
# stashed = "📦"
modified = "M/"
staged = "A/"
renamed = "R/"
deleted = "D/"

[memory_usage]
disabled = false
show_percentage = true
show_swap = true
threshold = -1
style = "bold dimmed green"
format = "via $symbol [ram:${ram_pct}( | swap:${swap_pct})]($style) "

[time]
disabled = false
