#!/bin/sh

alias f="rg -. \
  -g '!.git/' \
  -g '!*.gen.go' \
  -g '!*.lock' \
  -g '!*.snap' \
  -g '!*.svg' \
  -g '!go.sum' \
  -g '!package-lock.json' \
  -g '!pnpm-lock.yaml' \
  -g '!*.config.mjs' \
  -g '!*.config.ts' \
"

check () {
  if [[ $(eval $1 | wc -l) -ne 0 ]]; then
    echo "\n${BASH_LINENO[0]}: $1"
    eval $1
  fi
}

echo '---------- comment -----------------------------------------------------'
# コメントは最低限。
f '^\s+\* '
f '/\* (?!eslint-disable|@ts-expect-error)' -P
f '// (?!eslint-disable|@ts-expect-error)' -P

# eslint-disableは禁止。（eslint-disable-next-lineを使用する。）
check "f 'eslint-disable '"

echo '---------- HTML & CSS --------------------------------------------------'
# 下記以外のHTML要素は禁止。
check "f '\s<(?!div|ul|li|form|label|input|textarea|select|option|span|a|button|img|svg|[A-Z]|=|>|/)' -g '*.tsx' -P"
# マジックナンバーは禁止。
check "f '#[a-fA-F0-9]{6}'"
check "f '\-(50|[1-9]00|950)' -g '*.tsx'"

echo '---------- TypeScript --------------------------------------------------'
# type
check "f '[rR]eadonly'"
check "f '\bnever\b'" # unknownではない？
check "f '\b(Array|Boolean|Number|Object|String|Symbol)\b'"
check "f '\b(Parameters|ReturnType)\b'"
# statement
check "f 'const \w+: (?!FC|Next|Viewport)' -P" # 型注釈は禁止。
check "f 'const \{.*\}: .* ='" # 型注釈は禁止。
check "f 'export (type )?\{'"
check "f 'import type'"
check "f 'private '" # #を使用する。
check "f 'public '"
check "f 'type \w+ = \{.*\}'" # 改行する。
check "f '(?<!as const )satisfies' -P"
check "f '\?:' -g '!*.tsx'"
# other
check "f 'process.env.NODE_ENV.*production'" # developmentを使用する。（フェイルセーフ）
check "f '\bev'" # eを使用する。
check "f '\w\[\d+\]'" # .atを使用する。
# オブジェクトは改行する。（destructuring, shorthand property namesを除く。）
# check "f '\{ .*:.*,.* \}' -g '!*.test.ts' -g '!*.test.tsx'" # 2要素以上
# check "f '\{ .*,.*:.* \}' -g '!*.test.ts' -g '!*.test.tsx'" # 2要素以上
check "f '\{ .*:.* \}' -g '!*.test.ts' -g '!*.test.tsx' --color always | f -v 'lang: x'"

echo '---------- as const付与漏れ ------------------------------------------------'
f 'const (?!config|dict|viewport).* = \{' -P

echo '---------- React -------------------------------------------------------'
check "f 'cloneElement'"
check "f 'ComponentPropsWith'"
check "f 'dangerouslySetInnerHTML'"
check "f 'document.write'"
check "f 'Dispatch'"
check "f 'flushSync'"
check "f 'forwardRef'"
check "f 'JSX\.Element'"
check "f 'memo'"
check "f 'ReactNode'"
check "f 'React\.'"
check "f 'suppressHydrationWarning'"
check "f 'useCallback'"
check "f 'useMemo'"
check "f '\bChildren\b'"

echo '---------- Next.js -----------------------------------------------------'
# MetadataはPageでのみ使用する。（RootLayoutを除く。）
check "f '\bMetadata\b' -g '!*page.tsx' -g '!app/\[lang\]/layout.tsx'"

# 下記は禁止。
check "f 'next/image' -g '*.tsx'"
check "f 'next/router'"

# https://zenn.dev/dozo13189/articles/72a8f087b382cf
check "f '<Link (?!.*prefetch)' -g '*.tsx' -P"
# check "f '<Link (?!.*scroll)'   -g '*.tsx' -P"
f '<Link$' -g '*.tsx'

echo '---------- use client付与漏れ ----------------------------------------------'
f "^'use client';" -g '*.tsx' -l | sort > lint-tmp-1.txt
f '\b(on|use)[A-Z]' -g '*.tsx' -l | sort > lint-tmp-2.txt
comm -3 lint-tmp-1.txt lint-tmp-2.txt
rm -f   lint-tmp-1.txt lint-tmp-2.txt

echo '---------- use server付与漏れ ----------------------------------------------'
f "^'use server';" -l | sort > lint-tmp-1.txt
f '' -g '*function.ts' -l | sort > lint-tmp-2.txt
comm -3 lint-tmp-1.txt lint-tmp-2.txt
rm -f   lint-tmp-1.txt lint-tmp-2.txt

echo '---------- server-only付与漏れ ---------------------------------------------'
# 原則、ファイル全てにserver-onlyをimportする。
# 例外
# - クライアントコンポーネントの場合
# - 特定のファイル名の場合
f "^'use client';" -g '*.tsx' -l | sort > lint-tmp-1.txt
f "^import 'server-only';" \
  -g 'app/**' -g 'lib/**' \
  -g '!app/\[lang\]/globals.css' \
  -g '!*hook.ts' -g '!*hook.tsx' \
  -g '!*index.ts' -g '!*index.tsx' \
  -g '!*.test.ts' -g '!*.test.tsx' \
  --files-without-match | sort > lint-tmp-2.txt
comm -3 lint-tmp-1.txt lint-tmp-2.txt
rm -f   lint-tmp-1.txt lint-tmp-2.txt

echo '---------- Vitest ------------------------------------------------------'
# toStrictEqual以外のアサーションメソッドは禁止。
check "f 'toBe' -g '*.test.ts' -g '*.test.tsx'"
