#!/bin/sh

set -eu

branches=(develop main master)
current=$(git branch --show-current)
for branch in ${branches[@]}; do
  if [[ $branch == $current ]]; then
    echo "❌do not push $branch"
    exit 1
  fi
done

echo "✅$(basename $0)"
