#!/bin/sh

set -eu

asdf plugin add golang https://github.com/kennyp/asdf-golang.git
asdf plugin add java https://github.com/halcyon/asdf-java.git
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf plugin add rust https://github.com/code-lever/asdf-rust.git
