#!/bin/sh

set -eu

afplay ~/dotfiles/claude/hooks/終わりました！.mp3
echo '-'
date '+%Y-%m-%d %H:%M:%S（%Z）'
if [[ $(date +%-d) -lt 15 ]]; then
  since=$(date -v-1m +%Y%m15)
  until=$(date +%Y%m15)
else
  since=$(date +%Y%m15)
  until=$(date -v+1m +%Y%m15)
fi
npx ccusage@latest --since $since --until $until --json \
| jq -r '"約\(.totals.totalCost * 150 | round)円（$\(.totals.totalCost * 100 | round / 100)）"'
